#!/bin/bash

# * Draft: 2021-08-09 (Mon)

# install_google_cloud_sdk



python --version
curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-340.0.0-linux-x86_64.tar.gz
tar -xvf google-cloud-sdk-340.0.0-linux-x86_64.tar.gz
./google-cloud-sdk/install.sh
./google-cloud-sdk/bin/gcloud init

