#!/bin/bash
#  gcp2slurm0 (gsutil cp) to slurm0
#    https://cloud.google.com/storage/docs/gsutil/commands/cp
#
#  `gsutil cps`
#    copy data between your local file system and the cloud
#
#   Examples:
#     # Upload all text files to a bucket
#     $ gsutil cp *.txt gs://$MY_BUCKET
#
#     # Download all text files from a bucket
#     $ gsutil cp gs://$MY_BUCKET/*.txt .
#
#     # The -r option to copy an entire directory tree
#     $ gsutil cp -r $DIR gs://$MY_BUCKET
#
#     # The -m option for a parallel multi-threaded/multi-processing copy
#     $ gsutil -m cp -r $DIR gs://$MY_BUCKET
#
#     # The -I option to specify a list
#     #   to upload
#     $ cat $FILE_LIST | gsutil -m cp -I gs://$MY_BUCKET
#
#     #   to upload
#     $ cat $FILE_LIST | gsutil -m cp -I $DIR

# Function definition
run() {
  COMMAND=$1
  echo "$COMMAND"
  eval $COMMAND
}

# Check if $1 is empty
if [ -z "$1" ]; then
  echo "Usage: $0 <filename>"
  exit 1
fi

# Save the value in $1
FILENAME=$1

# You may change this part
#USER_TAG=${1:-tkim}
USER_TAG=${2:-slurm0}
BUCKET_NAME=${3:-object-storage}
# https://cloud.google.com/compute/docs/regions-zones
REGION=${4:-us-central1}
UNIQUE_BUCKET_NAME=$USER_TAG-$BUCKET_NAME-$REGION
# You may change this part

MY_BUCKET=$UNIQUE_BUCKET_NAME
run "gsutil cp $FILENAME gs://$MY_BUCKET"
