#!/bin/bash
# gssh_hub_vm

# Function definition
run() {
  COMMAND=$1
  echo "$COMMAND"
  eval $COMMAND
}

# https://cloud.google.com/compute/docs/regions-zones
REGION=${1:-us-central1}
echo "REGION=$REGION"
echo "Setting the associated variables automatically..."

INSTANCE_NAME=hub-${REGION}
PROJECT_ID=$(gcloud config list --format 'value(core.project)')
if [[ -z "$PROJECT_ID" ]]; then
  echo "PROJECT_ID is empty because the core.project property is not displayed."
  echo "This means that you haven't explicitly set a default project for the gcloud CLI."
  echo "Please set your project by running:"
  echo "  $ gcloud config set project PROJECT_ID"
  echo "To check the PROJECT_ID, go to Google Cloud Console and click Navigation Menu."
  echo "Go to Cloud overview > Dashboard and check Project ID in the Project Info card."
  exit 1
fi
ZONE=a
LOCATION=$REGION-$ZONE

run "gcloud compute ssh $INSTANCE_NAME --project=$PROJECT_ID --zone=$LOCATION"
