#!/bin/bash
#  make_an_object_publicly_readable
#    https://cloud.google.com/storage/docs/access-control/making-data-public

# Function definition
run() {
  COMMAND=$1
  echo "$COMMAND"
  eval $COMMAND
}

export PROJECT_ID=$(gcloud config list --format 'value(core.project)')
if [[ -z "$PROJECT_ID" ]]; then
  echo "PROJECT_ID is empty because the core.project property is not displayed."
  echo "This means that you haven't explicitly set a default project for the gcloud CLI."
  echo "Please set your project by running:"
  echo "  $ gcloud config set project PROJECT_ID"
  echo "To check the PROJECT_ID, go to Google Cloud Console and click Navigation Menu."
  echo "Go to Cloud overview > Dashboard and check Project ID in the Project Info card."
  exit 1
fi
export USER_TAG=${2:-tkim}
# https://cloud.google.com/compute/docs/regions-zones
export REGION=${1:-us-central1}
echo "REGION=$REGION"
export LOCATION=$REGION
export BUCKET_NAME=${3:-public-bucket}
export UNIQUE_BUCKET_NAME=$USER_TAG-$BUCKET_NAME-$LOCATION
export OBJECT_NAME=${4:-train_data.jsonl}

# https://cloud.google.com/storage/docs/access-control/making-data-public#objects
echo "Making individual objects publicly readable ..."
run "gcloud storage objects update gs://$UNIQUE_BUCKET_NAME/$OBJECT_NAME --add-acl-grant=entity=AllUsers,role=READER"
