#!/bin/bash
#  make_all_objects_in_a_bucket_publicly_readable
#    https://cloud.google.com/storage/docs/access-control/making-data-public

# Function definition
run() {
  COMMAND=$1
  echo "$COMMAND"
  eval $COMMAND
}

PROJECT_ID=$(gcloud config list --format 'value(core.project)')
if [[ -z "$PROJECT_ID" ]]; then
  echo "PROJECT_ID is empty because the core.project property is not displayed."
  echo "This means that you haven't explicitly set a default project for the gcloud CLI."
  echo "Please set your project by running:"
  echo "  $ gcloud config set project PROJECT_ID"
  echo "To check the PROJECT_ID, go to Google Cloud Console and click Navigation Menu."
  echo "Go to Cloud overview > Dashboard and check Project ID in the Project Info card."
  exit 1
fi
USER_TAG=${2:-tkim}
# https://cloud.google.com/compute/docs/regions-zones
REGION=${1:-us-central1}
echo "REGION=$REGION"
LOCATION=$REGION
BUCKET_NAME=${3:-public-bucket}
UNIQUE_BUCKET_NAME=$USER_TAG-$BUCKET_NAME-$LOCATION

# https://cloud.google.com/storage/docs/access-control/making-data-public#buckets
echo "Making all objects in a bucket publicly readable ..."
run "gcloud storage buckets add-iam-policy-binding gs://$UNIQUE_BUCKET_NAME --member=allUsers --role=roles/storage.objectViewer"
