#!/bin/bash
# add-iam-policy-binding

# Function definition
run() {
  COMMAND=$1
  echo "$COMMAND"
  eval $COMMAND
}


export PROJECT_ID=$(gcloud config list --format 'value(core.project)')
if [[ -z "$PROJECT_ID" ]]; then
  echo "PROJECT_ID is empty because the core.project property is not displayed."
  echo "This means that you haven't explicitly set a default project for the gcloud CLI."
  echo "Please set your project by running:"
  echo "  $ gcloud config set project PROJECT_ID"
  echo "To check the PROJECT_ID, go to Google Cloud Console and click Navigation Menu."
  echo "Go to Cloud overview > Dashboard and check Project ID in the Project Info card."
  exit 1
fi

export TYPE=user
export PRINCIPAL=admin@thekim.altostrat.com
export MEMBER=$TYPE:$PRINCIPAL

# https://cloud.google.com/iam/docs/understanding-roles#compute.instanceAdmin.v1
export ROLE=roles/compute.instanceAdmin.v1

export SERVICE_ACCOUNT_EMAIL=$(gcloud iam service-accounts list \
    --format='value(email)' \
    --project=$PROJECT_ID \
    --filter='displayName: Custom Service Account')
echo $SERVICE_ACCOUNT_EMAIL

# gcloud iam service-accounts add-iam-policy-binding --help
run "gcloud iam service-accounts add-iam-policy-binding \
--role=$ROLE \
--member=$MEMBER \
--project $PROJECT_ID"

# ERROR: (gcloud.iam.service-accounts.add-iam-policy-binding) INVALID_ARGUMENT: Role roles/compute.instanceAdmin.v1 is not supported for this resource.
# You are trying to grant a role to a service account that is not supported for that resource.
#run "gcloud iam service-accounts add-iam-policy-binding $SERVICE_ACCOUNT_EMAIL \
#--project $PROJECT_ID \
#--member=$MEMBER \
#--role=$ROLE"
# ERROR: (gcloud.iam.service-accounts.add-iam-policy-binding) INVALID_ARGUMENT: Role roles/compute.instanceAdmin.v1 is not supported for this resource.

# Q: Can I use gcloud command to add a role to a principal?
# A: I added it on Google Cloud Console. But I'm wondering if the same is possible with a gcloud command.
